import { model } from "@medusajs/framework/utils"

/**
 * `erpnext_setting` — singleton row for the Medusa-side ERPNext sync.
 *
 * One row keyed by `singleton_key = "default"`, so the admin UI is one
 * GET / one POST. Connection values fall back to env for bootstrap
 * (`ERPNEXT_URL`, `ERPNEXT_API_KEY`/`SECRET`, `ERPNEXT_FRAPPE_WEBHOOK_SECRET`,
 * `MEDUSA_BACKEND_URL`), so a fresh deploy works before anyone saves the
 * settings page.
 *
 * Secrets are stored as plaintext, like other settings models; the admin
 * GET masks them to a 3+3 preview. Treat the DB and its backups as
 * sensitive.
 *
 * `enable_sync = false` → every job and route no-ops without writing rows.
 */
export const ErpnextSetting = model.define("erpnext_setting", {
    /**
     * Consecutive failed pushes to ERPNext. Reset to zero the moment one
     * succeeds. See ../breaker.ts for why it is consecutive and not total.
     */
    consecutive_failures: model.number().default(0),

    /**
     * Set when the failures above reached `trip_after`. While it is set,
     * pushes are skipped rather than attempted and the retry job lets one
     * through per run to find out whether ERPNext has come back.
     */
    tripped_at: model.dateTime().nullable(),

    /** Consecutive failures before we stop trying. Ten by default. */
    trip_after: model.number().default(10),

    id: model.id().primaryKey(),
    /** Always "default" — enforces single-row semantics. The unique
     *  index on this column lives in the migration. */
    singleton_key: model.text().default("default"),

    /**
     * What may happen when a product is created in Medusa: "off",
     * "link" (attach to an existing Item only, the default) or "create".
     * See ./product-policy.ts for why this is the one catalogue decision
     * that belongs on this side.
     */
    medusa_product_policy: model.text().default("link"),

    // ── Master toggle ────────────────────────────────────────────────
    /** Kill switch. When false, `forwardEvent` short-circuits and
     *  doesn't write a row. Mirror of Frappe's `Medusa Settings.
     *  enable_sync`. */
    enable_sync: model.boolean().default(true),

    // ── Connection ───────────────────────────────────────────────────
    /** Base URL of the ERPNext site, e.g. `https://erp.example.com`.
     *  Trailing slash is stripped by the service. Empty → ERPNEXT_URL. */
    erpnext_url: model.text().nullable(),

    /** Where ERPNext reaches this store. The Frappe Webhooks POST to
     *  `<medusa_public_url>/webhooks/erpnext-inbound`. Empty →
     *  MEDUSA_BACKEND_URL. */
    medusa_public_url: model.text().nullable(),

    /**
     * The DocTypes that carry the `medusa_sync` selection field, each
     * with its mode: `[{doctype:"Item", mode:"allow"|"deny"}]`. See
     * ../selection.ts. Empty means `[{Item, allow}]`.
     */
    sync_doctypes: model.json().nullable(),

    /** When "Set up ERPNext" last ran, and what it found and did — the
     *  per-item report from ../erpnext-setup.ts. */
    erpnext_setup_at: model.dateTime().nullable(),
    erpnext_setup_report: model.json().nullable(),

    /** ISO 3166 region the `phone` transform assumes for a number with no
     *  country code. IN unless somebody says otherwise. */
    phone_region: model.text().default("IN"),

    /**
     * HMAC-SHA256 secret every Frappe Webhook row signs with
     * (`X-Frappe-Webhook-Signature`). Generated by "Set up ERPNext" when
     * empty and written into the Webhook rows by it; the inbound route
     * verifies with the same value. Empty → ERPNEXT_FRAPPE_WEBHOOK_SECRET.
     */
    frappe_webhook_secret: model.text().nullable(),

    /** ERPNext API key/secret (`Authorization: token key:secret`) for
     *  everything this side asks ERPNext: the pull, the setup, the meta
     *  reads. The API user needs System Manager for the setup. */
    erpnext_api_key: model.text().nullable(),
    erpnext_api_secret: model.text().nullable(),

    // ── HTTP behaviour ───────────────────────────────────────────────
    /** Per-request timeout in ms. Default 15s — tuned so a slow Frappe
     *  job has time to write a sync log row but the Medusa worker
     *  doesn't get pinned. */
    request_timeout_ms: model.number().default(15000),

    // ── Retry policy (read by the future retry cron) ─────────────────
    /** When true, a cron job auto-retries `failed` rows in
     *  `erpnext_sync_event`. Manual retry via the admin route is
     *  always available regardless of this flag. */
    auto_retry_failed: model.boolean().default(true),

    /** Stop retrying a row after this many total attempts. Prevents
     *  poison events from hammering ERPNext forever. */
    auto_retry_max_attempts: model.number().default(5),

    /** Minimum backoff floor in minutes between retries of the same
     *  event. The actual interval is exponential up to a cap; this
     *  is the smallest possible value. */
    auto_retry_min_interval_minutes: model.number().default(15),

    // ── Operational state ────────────────────────────────────────────
    /** Set when an admin clicks "Run full resync". Mirrors Frappe's
     *  `Medusa Settings.last_full_sync_at` on the other side, used
     *  for audit + as a soft cooldown. */
    last_full_resync_at: model.dateTime().nullable(),

    /**
     * Outbound safety valve. When non-empty, ONLY records whose
     * identity matches one of these entries are pushed to ERPNext;
     * everything else is skipped and logged as `not_in_allowlist`.
     *
     * Entries are newline- or comma-separated and matched
     * case-insensitively against the record's `id`, `email`, `handle`,
     * `display_id` and `external_id`.
     *
     * Why this exists: pointing a production Medusa at a non-production
     * ERPNext is a normal thing to want while integrating, but it would
     * otherwise stream every customer's personal data onto that box. An
     * allowlist makes "sync these three test records and nothing else"
     * expressible without disabling sync entirely.
     *
     * EMPTY = no restriction (all records push). That's the historical
     * behaviour and stays the default.
     */
    push_allowlist: model.text().nullable(),

    /**
     * How long to keep `erpnext_sync_event` rows before the daily prune
     * deletes them. Defaults to 180 days — comfortably past the
     * three-month window operators need to answer "did this customer
     * ever sync, and what happened".
     *
     * 0 disables pruning entirely (keep forever). Sync events carry the
     * payload, which on a Customer mapping means personal data, so
     * "forever" is a deliberate choice rather than the default.
     */
    log_retention_days: model.number().default(180),

    // ── Where a pushed document lands (Phase 2) ──────────────────────
    /** ERPNext Company the documents belong to. Empty → Global Defaults. */
    erpnext_company: model.text().nullable(),
    /** Selling price list on Sales Orders and Invoices. Empty → Selling Settings. */
    erpnext_price_list: model.text().nullable(),
    /** What a new Customer gets. Empty → ERPNext's own defaults. */
    erpnext_customer_group: model.text().nullable(),
    erpnext_territory: model.text().nullable(),
    /** Account head that books an order's shipping as an "Actual" charge.
     *  Empty → shipping is not booked and the sync row says so. */
    erpnext_shipping_account: model.text().nullable(),
    /** Sales Taxes and Charges Template applied to sales documents. */
    erpnext_taxes_template: model.text().nullable(),

    // ── Stock and prices, ERPNext → Medusa (Phase 3) ─────────────────
    /** Move stock levels from the warehouse below to the stock location. */
    sync_stock: model.boolean().default(false),
    /** Move selling prices on `erpnext_price_list` onto the variants. */
    sync_prices: model.boolean().default(false),
    /** The one ERPNext warehouse that feeds this store. */
    erpnext_warehouse: model.text().nullable(),
    /** The Medusa stock location the levels are written to. */
    medusa_stock_location_id: model.text().nullable(),
    /** Buffer held back from every level; an Item's own safety_stock wins when set. */
    erpnext_safety_stock: model.number().default(0),

    // ── Orders and invoices (this store's choice; honoured by the push) ─
    /** "Sales Order" | "Sales Invoice" | "Sales Order and Sales Invoice". */
    order_document: model.text().nullable(),

    /**
     * "erpnext": ERPNext numbers every invoice and sends it here.
     * "store": this store numbers its own, as `store_invoice_prefix` and a
     * running number, and ERPNext sends nothing back.
     */
    invoice_numbering: model.text().default("erpnext"),
    store_invoice_prefix: model.text().nullable(),
    /** The next running number. Advanced in one UPDATE so two orders
     *  placed together never share one. */
    store_invoice_next: model.number().default(1),
    send_invoice_to_store: model.boolean().default(false),
    record_payments: model.boolean().default(false),

    // ── Where invoice PDFs are kept (this store's choice) ────────────
    /** "local": a private directory, never under the public static dir.
     *  "s3": an S3-compatible bucket, read only through the store route. */
    invoice_storage: model.text().default("local"),
    invoice_local_dir: model.text().nullable(),
    s3_bucket: model.text().nullable(),
    s3_region: model.text().nullable(),
    /** For S3-compatible services (R2, MinIO, Hetzner). Empty for AWS. */
    s3_endpoint: model.text().nullable(),
    s3_prefix: model.text().nullable(),
    s3_force_path_style: model.boolean().default(false),
    s3_access_key_id: model.text().nullable(),
    s3_secret_access_key: model.text().nullable(),

    /** Free-text ops notes — escalation contacts, known quirks, etc. */
    notes: model.text().nullable(),

    /** User id (admin) who last saved the row. Useful when triaging
     *  "who turned sync off at 3 AM". */
    updated_by_user_id: model.text().nullable(),
})
